NextJS Rewrite
ScottyLabs/scottylol pull request #52
Opened 2022-10-03 16:41 UTC by Adrastopoulos

# Description

This is my attempt at a rewrite of the site and search engine with nextjs + typescript. Multiple styling improvements have been made, as well as automatic redirects to `/help` when an unknown route is accessed. Deployment (`ecosystem.config.js`) and `README.md` may need further updates, please review.

Closes #37

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] Linting and deployment scripts, valid and invalid queries

**Test Configuration**:

- Node.js version: `v18.9.0`
- Desktop/Mobile: Desktop
- OS: Windows
- Browser: Chrome

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2022-10-21 05:01 UTC, hdavidethan requested changes
Overall, this looks good. I have some comments on the rules you used on ESLint and some nits on React style.

In general, it's not a very good idea to disable too many rules when following a style guide.

2022-10-21 05:01 UTC, hdavidethan commented on .eslintrc.json
> +		"@typescript-eslint/indent": [2, "tab"],
Prefer 2 spaces. Tabs show up much larger on GitHub and are inconsistent between different environments.

2022-10-21 05:01 UTC, hdavidethan commented on .eslintrc.json
> +		"max-len": "off",
Reason for this?

2022-10-21 05:01 UTC, hdavidethan commented on .eslintrc.json
> +		"no-bitwise": "off",
I think it might be a good idea to keep these ones on. These rules try to prevent some bad coding behaviors.

2022-10-21 05:01 UTC, hdavidethan commented on .eslintrc.json
> +    "airbnb-base",
I approve of Airbnb's style guide. I'm just putting this for future reference: https://github.com/airbnb/javascript

2022-10-21 05:01 UTC, hdavidethan commented on src/pages/help.tsx
> +};
Declaring Props at the start is good. I think you can also make this an interface

```typescript
interface Props {
  helpInfo: CommandHelpInfo[];
}
```

2022-10-21 05:01 UTC, hdavidethan commented on src/pages/help.tsx
> +const HelpPage: React.FC<Props> = ({ helpInfo }) => (
Write this as a named function

```typescript
function HelpPage({helpInfo}: Props) { ... }
```
If you have to put a return type, it could be `JSX.Element` but try not to use `React.FC`.

Also refer to Airbnb's React style guide: https://github.com/airbnb/javascript/tree/master/react

2022-10-21 05:01 UTC, hdavidethan commented on src/pages/_document.tsx
> +	static async getInitialProps(ctx: DocumentContext) {
`getInitialProps` is not recommended in NextJS for React 18+. Is there a reason for using this?

2022-10-21 05:01 UTC, hdavidethan commented on src/pages/_document.tsx
> +class MyDocument extends Document {
Use functional components instead of class components.

2022-10-21 05:17 UTC, Adrastopoulos commented on .eslintrc.json
> +		"no-bitwise": "off",
This eslintconfig was pulled from an ancient project that I had on hand - so, many parts are indeed extraneous and unneeded. We can certainly simplify this down to the barebones and go from there.

2022-10-21 05:22 UTC, Adrastopoulos commented on src/pages/_document.tsx
> +	static async getInitialProps(ctx: DocumentContext) {
This *was* the default custom `_document` given by [nextjs](https://nextjs.org/docs/advanced-features/custom-document) when I made the pull, looks like they updated.

2022-10-21 05:25 UTC, Adrastopoulos commented on src/pages/_document.tsx
> +	static async getInitialProps(ctx: DocumentContext) {
Followup - they have a specific version for typescript projects.

2022-10-21 05:31 UTC, Adrastopoulos commented
In the spirit of good style, prettier is a must, as well as a plugin that implements prettier formatting suggestions into the linter.

2022-10-21 16:29 UTC, hdavidethan commented
Yes, I think we should use Prettier. I think we enforce the Prettier format as part of the lint rules on the Lost and Found repo.

2022-10-21 17:26 UTC, Adrastopoulos commented on src/pages/_document.tsx
> +	static async getInitialProps(ctx: DocumentContext) {
This file is meant to stay as a class since it extends the default Document class.

2022-10-21 17:27 UTC, Adrastopoulos commented on src/pages/help.tsx
> +const HelpPage: React.FC<Props> = ({ helpInfo }) => (
Resolved by [0f0bf4a](https://github.com/ScottyLabs/scottylol/pull/52/commits/0f0bf4aafcc365b9d14f31ed9b9da3ac210d54ea)

2022-10-21 17:27 UTC, Adrastopoulos commented on src/pages/help.tsx
> +};
[0f0bf4a](https://github.com/ScottyLabs/scottylol/pull/52/commits/0f0bf4aafcc365b9d14f31ed9b9da3ac210d54ea)

2022-10-21 17:27 UTC, Adrastopoulos commented on .eslintrc.json
> +    "airbnb-base",
[ea9ae42](https://github.com/ScottyLabs/scottylol/pull/52/commits/ea9ae4277e3a2a8d30df9f1f73d10cb4e0adf722)

2022-10-21 17:28 UTC, Adrastopoulos commented on .eslintrc.json
> +		"max-len": "off",
[ea9ae42](https://github.com/ScottyLabs/scottylol/pull/52/commits/ea9ae4277e3a2a8d30df9f1f73d10cb4e0adf722)

2022-10-21 17:28 UTC, Adrastopoulos commented on .eslintrc.json
> +		"@typescript-eslint/indent": [2, "tab"],
[ea9ae42](https://github.com/ScottyLabs/scottylol/pull/52/commits/ea9ae4277e3a2a8d30df9f1f73d10cb4e0adf722)

2022-11-04 21:16 UTC, hdavidethan approved these changes
Thanks for making the changes!

[![LGTM](https://lgtm.lol/p/759)](https://lgtm.lol/i/759)

2022-11-04 21:20 UTC, hdavidethan commented
@Adrastopoulos Please resolve merge conflicts

2022-11-05 17:22 UTC, hdavidethan approved these changes

2022-11-05 17:23 UTC, merged